version: '3.0'
services:

  web:
    build:
        context: .
        dockerfile: docker/apache/Dockerfile
        args:
            uid: ${UID}
    environment:
        - APACHE_RUN_USER=#${UID}
        - APACHE_RUN_GROUP=#${UID}
    restart: unless-stopped
    volumes: 
        - ./src:/var/www/html
        - ./apache_log:/var/log/apache2
    ports:
        - 80:80
    depends_on: 
        - db
    links:
        - db
  db:
    image: mysql:8.0
    container_name: db
    command: --sql_mode="" --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql-db:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 10
  adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
volumes:
  mysql-db:
  src: